;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="DamageType.Chemical",DevComment="")
+GameplayTagList=(Tag="DamageType.Energy",DevComment="")
+GameplayTagList=(Tag="DamageType.Explosive",DevComment="")
+GameplayTagList=(Tag="DamageType.Generic",DevComment="")
+GameplayTagList=(Tag="DamageType.Kinetic",DevComment="")
+GameplayTagList=(Tag="GameObject",DevComment="")
+GameplayTagList=(Tag="GameObject.AbandonedStation",DevComment="")
+GameplayTagList=(Tag="GameObject.Asteroid",DevComment="")
+GameplayTagList=(Tag="GameObject.InhabitedPlanet",DevComment="")
+GameplayTagList=(Tag="GameObject.Loot",DevComment="")
+GameplayTagList=(Tag="GameObject.Projectile",DevComment="")
+GameplayTagList=(Tag="GameObject.Ship",DevComment="")
+GameplayTagList=(Tag="GameObject.Star",DevComment="")
+GameplayTagList=(Tag="GameObject.Station",DevComment="")
+GameplayTagList=(Tag="GameObject.UninhabitedPlanet",DevComment="")
+GameplayTagList=(Tag="Item.TradeGood",DevComment="")
+GameplayTagList=(Tag="Race",DevComment="")
+GameplayTagList=(Tag="Race.Coalition",DevComment="")
+GameplayTagList=(Tag="Race.Coalition.Faeyan",DevComment="")
+GameplayTagList=(Tag="Race.Coalition.Gaalian",DevComment="")
+GameplayTagList=(Tag="Race.Coalition.Human",DevComment="")
+GameplayTagList=(Tag="Race.Coalition.Maloq",DevComment="")
+GameplayTagList=(Tag="Race.Coalition.Peleng",DevComment="")
+GameplayTagList=(Tag="Race.Dominator",DevComment="")
+GameplayTagList=(Tag="Race.Dominator.Blazeroid",DevComment="")
+GameplayTagList=(Tag="Race.Dominator.Kelleroid",DevComment="")
+GameplayTagList=(Tag="Race.Dominator.Terronoid",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Droid",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Engine",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Flex",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.FuelTank",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Hull1",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Hull2",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Radar",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Scanner",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.ShieldGenerator",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.TractorBeam",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Weapon1",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Artifact.Weapon2",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Droid",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Engine",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Flex",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.FuelTank",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Hull",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Radar",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Scanner",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.ShieldGenerator",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.TractorBeam",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.1",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.2",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.3",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.4",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.5",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.6",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.7",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.8",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.9",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Equipment.Weapon.10",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative.ArmorNullification",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative.EquipmentCost",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative.EquipmentWeight",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative.ScannerDuration",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative.ShipMass",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Negative.Weapon.EnergyUse",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Accuracy",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.CargoCapacity",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DamageCoalition",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DamageDominator",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DamageEnergetic",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DamageExplosive",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DamageGlobal",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DamageKinetic",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.DroidRepair",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.EnergyCapacity",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.EnergyDissipation",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.EnergyEfficiency",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Evasion",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.FuelCapacity",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.HyperJumpRange",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.MaxHullPoints",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.MaximumDurability",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.MaxShieldPoints",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.MaxSpeed",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.RadarRange",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.ScannerStrength",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.ShieldGeneratorDamageBlock",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.ShipDamageResistance",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.ShipEnergeticResistance",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.ShipExplosiveResistance",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.ShipKineticResistance",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.TractorBeamRange",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.TractorBeamStrength",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon.Initiative",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon.MaxDamage",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon.MaxRange",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon.MinDamage",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon.MinRange",DevComment="")
+GameplayTagList=(Tag="SpaceShip.Stat.Positive.Weapon.TargetEnergyBuildup",DevComment="")

